-- all physical affs
whr.physical_affs = {
"paralysis",
"paresis",
"right_arm_broken",
"left_arm_broken",
"right_leg_broken",
"left_leg_broken",
"physical_disruption",
"haemophilia",
"asthma",
"impairment",
"clumsiness",
"vomiting",
"sensitivity",
"ringing_ears",
"lethargy",
"blood_poison",
"blood_curse",
"crippled_throat",
"sandrot",
"disfigurement",
"blisters",
"magic_fire",
"lightwound",
"ablaze",
"hypothermia",
"shivering",
"frozen",
"limp_veins",
"rend",
"exhausted",
"allergies",
"addiction",
"hypersomnia",
"heartflutter",
"whiplash",
"backstrain",
"sore_wrist",
"sore_ankle", 
"burnt_eyes",
"blurry_vision",
"migraine",
"deadening",
"ice_encased",
}

-- all mental affs
whr.mental_affs = {
"egocentric",
"stupidity",
"anorexia",
"epilepsy",
"mirroring",
"mental_disruption",
"peace",
"paranoia",
"hallucinations",
"dizziness",
"indifference",
"berserking",
"pacifism",
"lovers_effect",
"laxity",
"hatred",
"generosity",
"claustrophobia",
"vertigo",
"faintness",
"loneliness",
"agoraphobia",
"masochism",
"recklessness",
"weariness",
"impatience",
"confusion",
"dementia",
"nyctophobia",
"premonition"
}

whr.limb_affs = {
"head_bruised",
"head_bruised_critical",
"head_bruised_moderate",
"head_damaged",
"head_mangled",
"left_arm_amputated",
"left_arm_bruised",
"left_arm_bruised_critical",
"left_arm_bruised_moderate",
"left_arm_damaged",
"left_arm_dislocated",
"left_arm_mangled",
"left_leg_aputated",
"left_leg_bruised",
"left_leg_bruised_critical",
"left_leg_bruised_moderate",
"left_leg_damaged",
"left_leg_dislocated",
"left_leg_mangled",
"right_arm_amputated",
"right_arm_bruised",
"right_arm_bruised_critical",
"right_arm_bruised_moderate",
"right_arm_damaged",
"right_arm_dislocated",
"right_arm_mangled",
"right_leg_aputated",
"right_leg_bruised",
"right_leg_bruised_critical",
"right_leg_bruised_moderate",
"right_leg_damaged",
"right_leg_dislocated",
"right_leg_mangled",
"torso_bruised",
"torso_bruised_critical",
"torso_bruised_moderate",
"torso_damaged",
"torso_mangled",
}

whr.other_affs = {
"accursed",
"aeon",
"agony",
"baldness",
"blighted",
"body_odor",
"burnt_skin",
"collapsed_lung",
"commitment_fear",
"cracked_ribs",
"crippled",
"crippled_body",
"crushed_chest",
"destroyed_throat",
"dissonance",
"effused_blood",
"gloom",
"hellsight",
"hubris",
"hypochondria",
"idiocy",
"infested",
"itchy",
"justice",
"magnanimity",
"mauled_face",
"merciful",
"muscle_spasms",
"patterns",
"plodding",
"sadness",
"self-pity",
"shaderot_benign",
"shaderot_body",
"shaderot_heat",
"shaderot_spirit",
"shaderot_wither",
"shyness",
"slickness",
"smashed_throat",
"spinal_rip",
"squelched",
"stiffness",
"stormtouched",
"stuttering",
"superstition",
"thin_blood",
"voidgaze",
"voyria",
"weak_grip",
"withering",
"worrywart"
}

whr.writhe_affs = {
"writhe_armpitlock",
"writhe_bind",
"writhe_grappled",
"writhe_gunk",
"writhe_hoist",
"writhe_impaled",
"writhe_lure",
"writhe_necklock",
"writhe_ropes",
"writhe_statis",
"writhe_thighlock",
"writhe_transfix",
"writhe_vines",
"writhe_web"
}

-- all affs, total
whr.all_affs = {}
for _,aff in pairs(whr.physical_affs) do
  table.insert(whr.all_affs, aff)
end
for _,aff in pairs(whr.mental_affs) do
  table.insert(whr.all_affs, aff)
end
for _,aff in pairs(whr.other_affs) do
  table.insert(whr.all_affs, aff)
end


-- some stuff for Archivist curing
whr.shapes = {
  circle = {
    "merciful",
    "masochism",
    "berserking",
    "recklessness",
    --"sealing_circle"
  },
  triangle = {
    "laxity",
    "lovers_effect",
    "peace",
    "magnanimity",
    --"sealing_triangle"
  },
  square = {
    "dizziness",
    "faintness",
    "epilepsy",
    "shyness",
    --"sealing_square"
  }
}